[build]
builder = "NIXPACKS"
buildCommand = "cd packages/backend && pnpm install --frozen-lockfile && pnpm build"

[deploy]
startCommand = "cd packages/backend && pnpm prisma:migrate:deploy && pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
